package com.ahmedmeid.rstrntgmgt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DineInOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDineInOrderAllPropertiesEquals(DineInOrder expected, DineInOrder actual) {
        assertDineInOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertDineInOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDineInOrderAllUpdatablePropertiesEquals(DineInOrder expected, DineInOrder actual) {
        assertDineInOrderUpdatableFieldsEquals(expected, actual);
        assertDineInOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDineInOrderAutoGeneratedPropertiesEquals(DineInOrder expected, DineInOrder actual) {
        assertThat(expected)
            .as("Verify DineInOrder auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDineInOrderUpdatableFieldsEquals(DineInOrder expected, DineInOrder actual) {
        assertThat(expected)
            .as("Verify DineInOrder relevant properties")
            .satisfies(e -> assertThat(e.getOrderTime()).as("check orderTime").isEqualTo(actual.getOrderTime()))
            .satisfies(e -> assertThat(e.getTableNumber()).as("check tableNumber").isEqualTo(actual.getTableNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDineInOrderUpdatableRelationshipsEquals(DineInOrder expected, DineInOrder actual) {
        assertThat(expected)
            .as("Verify DineInOrder relationships")
            .satisfies(e -> assertThat(e.getRestaurant()).as("check restaurant").isEqualTo(actual.getRestaurant()));
    }
}
