package com.ahmedmeid.rstrntgmgt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllPropertiesEquals(MenuItem expected, MenuItem actual) {
        assertMenuItemAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAllUpdatablePropertiesEquals(MenuItem expected, MenuItem actual) {
        assertMenuItemUpdatableFieldsEquals(expected, actual);
        assertMenuItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemAutoGeneratedPropertiesEquals(MenuItem expected, MenuItem actual) {
        assertThat(expected)
            .as("Verify MenuItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemUpdatableFieldsEquals(MenuItem expected, MenuItem actual) {
        assertThat(expected)
            .as("Verify MenuItem relevant properties")
            .satisfies(e -> assertThat(e.getItemName()).as("check itemName").isEqualTo(actual.getItemName()))
            .satisfies(e -> assertThat(e.getItemDescription()).as("check itemDescription").isEqualTo(actual.getItemDescription()))
            .satisfies(e -> assertThat(e.getIngredients()).as("check ingredients").isEqualTo(actual.getIngredients()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").isEqualTo(actual.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuItemUpdatableRelationshipsEquals(MenuItem expected, MenuItem actual) {
        assertThat(expected)
            .as("Verify MenuItem relationships")
            .satisfies(e -> assertThat(e.getMenuCategory()).as("check menuCategory").isEqualTo(actual.getMenuCategory()));
    }
}
