package com.ahmedmeid.rstrntgmgt.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MenuCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryAllPropertiesEquals(MenuCategory expected, MenuCategory actual) {
        assertMenuCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertMenuCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryAllUpdatablePropertiesEquals(MenuCategory expected, MenuCategory actual) {
        assertMenuCategoryUpdatableFieldsEquals(expected, actual);
        assertMenuCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryAutoGeneratedPropertiesEquals(MenuCategory expected, MenuCategory actual) {
        assertThat(expected)
            .as("Verify MenuCategory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryUpdatableFieldsEquals(MenuCategory expected, MenuCategory actual) {
        assertThat(expected)
            .as("Verify MenuCategory relevant properties")
            .satisfies(e -> assertThat(e.getCategoryName()).as("check categoryName").isEqualTo(actual.getCategoryName()))
            .satisfies(
                e -> assertThat(e.getCategoryDescription()).as("check categoryDescription").isEqualTo(actual.getCategoryDescription())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMenuCategoryUpdatableRelationshipsEquals(MenuCategory expected, MenuCategory actual) {
        assertThat(expected)
            .as("Verify MenuCategory relationships")
            .satisfies(e -> assertThat(e.getMenu()).as("check menu").isEqualTo(actual.getMenu()));
    }
}
